mainfiles := "main.cpp simulator.cpp JobQueue.cpp"
otherfiles := "./schedulers/FIFO.cpp ./schedulers/SJF.cpp ./schedulers/FIFOQueue.cpp ./schedulers/STCF.cpp"

build:
    g++ -ggdb -Wall -Weffc++ -Wextra -Wconversion -Wsign-conversion \
    -std=c++23 \
    -o main \
    {{mainfiles}} \
    {{otherfiles}}

build-debug:
    g++ -ggdb -Wall -Weffc++ -Wextra -Wconversion -Wsign-conversion \
    -std=c++23 \
    -o main \
    -D DEBUG \
    {{mainfiles}} \
    {{otherfiles}}

build-release:
    g++ -O3 \
    -std=c++23 \
    -o main \
    {{mainfiles}}\
    {{otherfiles}}
